name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Validate version matches tag
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/v}"
          MANIFEST_VERSION=$(grep '"version"' custom_components/noaa_tides/manifest.json | cut -d'"' -f4)
          if [ "$TAG_VERSION" != "$MANIFEST_VERSION" ]; then
            echo "Tag version ($TAG_VERSION) does not match manifest version ($MANIFEST_VERSION)"
            exit 1
          fi
          echo "Version validated: $TAG_VERSION"

      - name: Create release notes
        run: |
          echo "# NOAA Tides v${{ github.ref_name }}" > RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "See [CHANGELOG](CHANGELOG.md) for details." >> RELEASE_NOTES.md

      - name: Upload release notes
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE_NOTES.md
          files: |
            CHANGELOG.md
